### ISSUE TITLE
Peer review for assignment 2

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/rip#40]
Starting the peer review for assignment 2

**Comment by Meghesh** [comment]
Let us know if you find any issues

**Comment by nawazkh** [comment]
Facing issue on running the jar for JSONParser.
"no main manifest attribute, in target/JSONParser-0.0.1-SNAPSHOT.jar"
Below is the snapshot:

<img width="947" alt="screen shot 2018-10-25 at 12 13 18 am" src="https://user-images.githubusercontent.com/25679594/47475749-f9ea4880-d7ea-11e8-8c4c-b48a80e8c07e.png">

**Comment by nawazkh** [comment]
Facing following error with MongoManager:

2018-10-24 23:58:19.994 ERROR 2872 --- [nio-8810-exec-1] o.a.c.c.C.[.[.[/].[InsertService]        : Servlet.service() for servlet [InsertService] in context with path [] threw exception [org.apache.thrift.transport.TTransportException] with root cause

org.apache.thrift.transport.TTransportException: null
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) ~[libthrift-0.11.0.jar!/:0.11.0]
	at org.apache.thrift.server.TServlet.doGet(TServlet.java:96) ~[libthrift-0.11.0.jar!/:0.11.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar!/:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by nawazkh** [comment]
On running Django vue try : 
Following is the error thrown.
nawazkh@js-17-86:~/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1$ sudo npm run dev

> django_vue_try1@1.0.0 dev /home/nawazkh/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1
> cross-env NODE_ENV=development webpack-dev-server --open --hot

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html
Unable to open browser. If you are running in a headless environment, please do not use the open flag.

Is it possible to configure this as a detached node? So that the user may not face this error?

**Comment by nawazkh** [comment]
Documentation is really good! Keep up the good work! 👍

**Comment by nawazkh** [comment]
As per the deliverables of this assignment. 
Service Discovery,
Continuous Deployment
Asynchronous Communication were expected. 

 Service Discovery and Continuous Deployment not achieved in this release

**Comment by jitendraselvam** [comment]
> On running Django vue try :
> Following is the error thrown.
> nawazkh@js-17-86:~/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1$ sudo npm run dev
> 
> > django_vue_try1@1.0.0 dev /home/nawazkh/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1
> > cross-env NODE_ENV=development webpack-dev-server --open --hot
> 
> Project is running at http://localhost:8080/
> webpack output is served from /dist/
> 404s will fallback to /index.html
> Unable to open browser. If you are running in a headless environment, please do not use the open flag.
> 
> Is it possible to configure this as a detached node? So that the user may not face this error?

> On running Django vue try :
> Following is the error thrown.
> nawazkh@js-17-86:~/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1$ sudo npm run dev
> 
> > django_vue_try1@1.0.0 dev /home/nawazkh/peerReview2/Front_end_module_1.0/rip/VueJs-django-CSVUploads/django_vue_try1
> > cross-env NODE_ENV=development webpack-dev-server --open --hot
> 
> Project is running at http://localhost:8080/
> webpack output is served from /dist/
> 404s will fallback to /index.html
> Unable to open browser. If you are running in a headless environment, please do not use the open flag.
> 
> Is it possible to configure this as a detached node? So that the user may not face this error?

It is not a problem with the configuration. The application is running but does not have permission to open up a web browser. You can try running it with a higher privileged user. 

refer: https://github.com/vuejs-templates/webpack-simple/issues/74
or you can try this
https://github.com/uber/kepler.gl/issues/161

In the next release we will remove the browser open option.

**Comment by jitendraselvam** [comment]
> As per the deliverables of this assignment.
> Service Discovery,
> Continuous Deployment
> Asynchronous Communication were expected.
> 
> Service Discovery and Continuous Deployment not achieved in this release

As per our wiki, we have mentioned our project goals in our wiki for [milestone 2](https://github.com/airavata-courses/rip/wiki/Assignment-2-Setup). We do not have the above mentioned requirements for this milestone. Our requirements might not align with the rest of the projects.
